### ISSUE TITLE
expose 4318 port from otel-collector?

### ISSUE THREAD

**Issue by jovezhong** [ClickHouse/ClickStack-helm-charts#31]
Hello, I installed the helm chart on GKE, using external ClickHouse. I don't see any data in HyperDX UI. I tried to follow https://clickhouse.com/docs/use-cases/observability/clickstack/getting-started/sample-data, but this will push data to "http://localhost:4318/v1", which is not available on my mac. I even configured portforward and it doesn't work.

The remote demo server https://clickhouse.com/docs/use-cases/observability/clickstack/getting-started/remote-demo-data is not working either (it mentioned [sql.clickhouse.com](https://sql.clickhouse.com/) at beginning but use https://sql-clickhouse.clickhouse.com for the configure. I login to the play UI and cannot run SQL query with that account)

<img width="1481" alt="Image" src="https://github.com/user-attachments/assets/69c2134a-2fbe-4d55-8461-138d056bee91" />

Too many things are broken..

Anyway, it'll be great if the default helm chart can expose 4318/4317 port if otel-collector is enabled, otherwise, hard to push data to hyperdx

**Comment by teeohhem** [comment]
Hi there. By default, port 4317 and 4318 is exposed in the chart for the otel-collector. Are you still having issues?

**Comment by jovezhong** [comment]
Hi @teeohhem , from https://github.com/hyperdxio/helm-charts/blob/main/charts/hdx-oss-v2/templates/ingress.yaml only the app server's 3000 port is exposed. I still having issue to push data to the otel-collector. Can I just push data to 4320 or 8000 of hyperdx app?

**Comment by teeohhem** [comment]
@jovezhong Ah you're having issues pushing data to the collector outside of the cluster. I see. This is a shortcoming in the chart. The ingress controller defined in the chart is optimized for the app. Given otel speaks http/grpc, i'm not sure exposing it through ingress is the way to go. 

Would something like this work for you in the meantime?

```kubectl patch svc <your-release-name>-otel-collector -p '{"spec":{"type":"LoadBalancer"}}'```

I'll work on a fix

**Comment by jovezhong** [comment]
Thanks. I changed it to LoadBalancer, it does open many ports but I cannot access to them

<img width="416" alt="Image" src="https://github.com/user-attachments/assets/9283e00e-c052-4948-bece-cc3dfa08a77b" />

It's a "Target-pool Network Load Balancer", I have opened 4318 on my 3 VM for the GKE. Anything else need to be configured?

**Comment by jovezhong** [comment]
Thanks you. Look forward to the new helm chart version

**Comment by jaysonsantos** [comment]
with the following you can kustomize it

kustomization.yaml
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: hdx-oss-v2
    namespace: hyperdx
    releaseName: my-reelase
    repo: https://hyperdxio.github.io/helm-charts
    valuesFile: values.yaml
    version: 0.5.1
namespace: hyperdx
generators:
  - secrets.yaml
patches:
  - path: patches.yaml

```

patches.yaml
```yaml

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-release-hdx-oss-v2-app-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  ingressClassName: traefik
  rules:
    - host: hyperdx.my.site
      http:
        paths:
          - backend:
              service:
                name: my-release-hdx-oss-v2-app
                port:
                  number: 3000
            path: /
            pathType: Prefix

---
apiVersion: v1
kind: Service
metadata:
  name: my-release-hdx-oss-v2-app
spec:
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-release-hdx-oss-v2-app-config
data:
  # APP_PORT: 443
  # API_PORT: 443
  FRONTEND_URL: "https://hyperdx.my.site"
  # HYPERDX_API_PORT: 443
  # HYPERDX_APP_PORT: 443
  HYPERDX_APP_URL: "https://hyperdx.my.site/app"
  NEXT_PUBLIC_OTEL_EXPORTER_OTLP_ENDPOINT: "https://hyperdx.my.site/otel/v1/traces"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-release-hdx-oss-v2-app
  annotations:
    reloader.stakater.com/auto: "true"
```

**Comment by jovezhong** [comment]
I tried v0.6.3 helm chart and still cannot make the otel ingestion work.

The doc on https://clickhouse.com/docs/use-cases/observability/clickstack/getting-started/sample-data shows
```bash
for filename in $(tar -tf sample.tar.gz); do
  endpoint="http://localhost:4318/v1/${filename%.json}"
  echo "loading ${filename%.json}"
  tar -xOf sample.tar.gz "$filename" | while read -r line; do
    echo "$line" | curl -s -o /dev/null -X POST "$endpoint" \
    -H "Content-Type: application/json" \
    -H "authorization: ${CLICKSTACK_API_KEY}" \
    --data-binary @-
  done
done
```

I assume http://localhost:4318/v1/ need to be replaced by the otel-collector IP. BTW, are you sure it's /v1/filename, not v1/logs or v1/metrics? Because I saw `path: /v1/(traces|metrics|logs)` in the paths mapping

Here is my values.yml
```yaml
replicaCount: 2
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi
clickhouse:
  enabled: false
otel:
  clickhouseEndpoint: tcp://clickhouse.demo.timeplus.com:9000
  opampServerUrl: "http://34.168.197.101:4320" #I cannot use http://hyperdx-hdx-oss-v2-app.default.svc.cluster.local:4320 as README suggested, got " dial tcp 34.118.237.88:4320: connect: connection refused"
hyperdx:
  ingress:
    enabled: true
    additionalIngresses:
      - name: otel-collector
        annotations:
          nginx.ingress.kubernetes.io/ssl-redirect: "false"
          nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
          nginx.ingress.kubernetes.io/use-regex: "true"
        ingressClassName: nginx
        hosts:
          - host: hyperdxotel.demo.timeplus.com
            paths:
              - path: /v1/(traces|metrics|logs)
                pathType: Prefix
                port: 4318
        tls:
          - hosts:
              - hyperdxotel.demo.timeplus.com
            # secretName: collector-tls
  clickhouseDatabase: demo
  appUrl: https://hyperdx.demo.timeplus.com
  defaultConnections: |
    [
      {
        "name": "External ClickHouse",
        "host": "clickhouse.demo.timeplus.com",
        "port": 8123,
        "username": "user",
        "password": "pwd"
      }
    ]

```

otel-collector

<img width="951" alt="Image" src="https://github.com/user-attachments/assets/80713b45-9a66-4c3b-be80-041c5fcd996a" />

otel-app

<img width="846" alt="Image" src="https://github.com/user-attachments/assets/93daa37d-c1fe-499f-88d8-39cead279a00" />

Let me know how to upload sample data or push new data to the clickstack. Thanks
